### ISSUE TITLE
Ajustes en la impresión de Secuencia de Trabajo ODT [1,5]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTL#100]
Realizar los siguientes ajustes en la impresión de secuencia de trabajo:

1. actualmente imprime en doble faz, cuando va a imprimir la 2da hoja tiene que avisar y pedir confirmación para dar tiempo a ingresar el papel
2.  el orden de las piezas debe ser el que queda luego del módulo de cosido de gtl lite, y los metros tienen que ser los del remito de entrada
3. los bloques de "SECTOR HÚMEDO", "SECTOR SECO" y "ESTAMPADO" deberían alinearse en forma horizontal, hoy están vertical. Además para "SECTOR HÚMEDO" se pide agrupar la info en 3 columnas: "químicos", "poliester" y "algodón" tal como está en el simulador.
4. el bloque "ESTAMPADO" no debería estar si no hay fórmula de ese proceso
5. agregar el código de color tanto en el encabezado como en el título de "SECTOR HÚMEDO".
6. agregar el usuario entre los 2 códigos de barra

![sec_de_trabajo](https://cloud.githubusercontent.com/assets/11740282/23229826/7b011d1e-f920-11e6-9737-1937a1f3d777.png)

**Comment by nacho270** [comment]
Tiempo: 1, 5h. Division de sector humedo en quimico, algodon y poliester. Agregado de color, usuario y piezas. Quedan dudas del sector seco y del doble faz.

**Comment by nacho270** [comment]
Total: 1,5 h. Se cierra con el #120
