### ISSUE TITLE
Implementar esquema de notificaciones al Terminar una ODT [13h]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTL#111]
Se pide implementar un esquema de notificaciones (GUI + lógica Backend) que emita alertas cada vez que una ODT pasa a estado TERMINADA. La alerta deberá indicar que ya es posible facturar la misma.

**Comment by nacho270** [comment]
Total: 3h. Investigacion + llegar a algo que funcione.

Tiempo total: 3h

**Comment by nacho270** [comment]
Total: 1h. Primer avance de UI
Tiempo acumualdo: 4h

**Comment by nacho270** [comment]
Agrego 3 h. Desarrollo backend (entidades, query, configuracion) + desarrollo en serio GUI. Falta probar

Tiempo acumulado: 7 h

**Comment by nacho270** [comment]
Agrego 30m. Separo generacion de notificaciones y envio.

Pendiente dialogo de visualizacion de notificaciones

TIempo acumulado: 7.5 hs.

**Comment by nacho270** [comment]
Agrego 1h. Dialogo para ver notificaciones

Acciones para notificaciones notificaciones

TIempo acumulado: 8.5 hs.

**Comment by nacho270** [comment]
Agrego 3,5h. Acciones post notificacion.

Acumulado: 12h

**Comment by nacho270** [comment]
Agrego 1 hora de correcciones graficas.

Total: 13h
