### ISSUE TITLE
ODT - Impresión de Secuencia de Trabajo [1h]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTL#120]
Reorganizar impresión de la secuencia de trabajo.
(es lo que no quedó funcionando en la fábrica el 16/05).
También agregar que avise cuando va a imprimir la 2da página así otorga tiempo para dar vuelta la hoja.

**Comment by nacho270** [comment]
Total: 1h.

Quedo masomenos... no se pudo hacer horizontal y depende de que haya pocas cosas en sector seco
