### ISSUE TITLE
Remito de Entrada - Cambios en el dialogo de alta/consulta/edición [1h]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTL#121]
Se piden hacer los siguientes cambios en el dialogo de RE:
1) Quitar IVA/CUIT/DIRECCION/LOCALIDAD
2) Condición de Venta debe traer sin editar el que tiene el cliente, si no tiene debe solicitar seleccionarlo (obligatorio) y luego actualizarlo en el cliente también.
3) Agregar los siguientes campos de texto (no obligatorios):
      - Artículo Cliente
      - Observaciones ODT
Aplicar los 2 primeros puntos al remito de entrada de 01 también.

**Comment by nacho270** [comment]
No hay clientes sin condicion de venta y es obligatorio para los nuevos. No fue necesario agregar la funcionalidad de que lo pida.

Total: 1h
