### ISSUE TITLE
Crear movimiento al ingresar un RS de tipo DEVOLUCION/REPROCESO S/CARGO [1,5h]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTL#126]
Se pide insertar un movimiento de monto cero al ingresar un remito de salida del tipo "devolución"/"reproceso sin cargo". Las ODTs relacionadas deberían quedar en estado FACTURADA.

Hacer script que haga estas 2 cosas en forma retroactiva en la A y en la B.

**Comment by nacho270** [comment]
Total: 1h.

**Comment by nacho270** [comment]
Agrego consulta RS.

Total: 1,5hs
