### ISSUE TITLE
Quitar campos en el dialogo de alta/consulta de RS [30m]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTL#127]
Se pide quitar los siguientes campos en el dialogo de alta/consulta de Remito de salida:
+ DIRECCION
+ LOCALIDAD
+ IVA
+ CUIT
+ CONDICION DE VENTA
luego del quitado de esos campos, acomodar NRO DE REMITO.

**Comment by nacho270** [comment]
Total: 30m
