### ISSUE TITLE
Implementar entrada de Cilindros [2h]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTL#145]
Implementar la salida de cilindros.
La entrada de cilindros (dibujos) se registaría al crear una FC s/Remito cuando se detecta que se cargaron cilindros, se debe preguntar la correspondencia entre esa cantidad y los dibujos. Cada dibujo debe tener como mínimo 1 cilindro y como máximo la cantidad de cilindros pero la suma total no debe sobrepasar la cantidad de cilindros. Cada dibujo creado debe tener los siguientes datos:
- nombre (opcional), lo ingresa el usuario 
- número, se calcula con la misma lógica que el ABM de Dibujos (1er dígito es la cant de cilindros, etc).
Una vez grabados, esos dibujos quedan asignados al cliente en cuestión. Además de crearlos, también se pueden elegir dibujos (sólo de ese cliente) previamente guardados con esta misma operación. 
De esta manera, se va llevando una cuenta de los dibujos que tiene cada cliente y después se puede implementar un remito de salida exclusivo para devolver los mismos.

**Comment by nacho270** [comment]
Total: 2h
