### ISSUE TITLE
ABM de Dibujos - Refactor [2h]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTL#146]
Se pide cambiar el ABM de dibujos y hacerlo parecido al módulo de consulta de ODTs/Remitos, agregando un filtro por cliente y trasladando todas sus funcionalidades. Si no se selecciona ningún cliente deberá traer todos. Además deberá existir una acción que permita quitar la asignación de un dibujo para un cliente dado.

**Comment by nacho270** [comment]
Total: 2h.
