### ISSUE TITLE
Implementar acción para dar salida a dibujos [3h]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTL#153]
Se pide implementar la salida de dibujos de clientes, se deberá hacer en la misma acción para dar salida de piezas pero con una solapa al lado de las de las ODTs que liste los dibujos que estén en condiciones de dar salida.

**Comment by nacho270** [comment]
30m: Mostrar dibujos para dar salida

**Comment by nacho270** [comment]
Agrego 1h: Generar y consultar RS dibujo.

Falta imprimir y contemplar el envio por mail.

Total: 1,5 h

**Comment by nacho270** [comment]
Agrego 0,5h. Dar salida a multiples dibujos

Falta imprimir y contemplar el envio por mail.

Total: 2h

**Comment by nacho270** [comment]
1h: Impresion RS dibujo.

Cierro porque me parece que no aplica el envio de emails para este caso.

Total: 3h.
