### ISSUE TITLE
Filtros en módulo de búsqueda de cheques [1,5h]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTL#154]
En el módulo de búsqueda de cheques se piden incorporar los siguientes filtros:
+ por importe (con "desde" y "hasta" que sean obligatorios)
+ por banco (combo)

**Comment by nacho270** [comment]
Controles graficos y validaciones.
Total: 30m.

**Comment by nacho270** [comment]
Agrego 1h: Querys para filtros + boton de reset de filtros en la cabecera.

Total: 1,5 h
