### ISSUE TITLE
Escaneo de datos de cheques [1h]

### ISSUE THREAD

**Issue by ignaciocicero** [nacho270/GTL#167]
Agregar un boton "escanear" en la pantalla de carga de cheque.
Debe levantar un dialogo donde se espera el escaneo del usuario y al salir autocompleta los campos.

Codigo banco: 3 caracteres
Sucursal: 3 caracteres
Codigo postal: 4 caracteres
Nro cheque: 8 caracteres
Nro cuenta: 11 caracteres

**Comment by nacho270** [comment]
UI de escaneo de cheque.

Total: 30m

**Comment by nacho270** [comment]
Agrego 30m: Cargar datos en controles despues de escanear.

Total:  1h.
