### ISSUE TITLE
Lista de precios + refactor necesario [107,5]

### ISSUE THREAD

**Issue by nacho270** [nacho270/GTL#17]
2 hs x 2 = 4hs de reunion

**Comment by diejavrom** [comment]
1.5 x 2 = 3hs de reunion

**Comment by diejavrom** [comment]
2 x 2 = 4hs de reunión

**Comment by nacho270** [comment]
Total: 11hs

**Comment by nacho270** [comment]
1h x 2 de diseno = 2hs

Total = 13 hs

**Comment by diejavrom** [comment]
Del commit anterior fueron: 17/08 --> 3.5 hrs, 18/08 --> 3.5 hrs y 19/08 --> 3 hrs. Subtotal = 10hrs
Total = 23 hs

**Comment by diejavrom** [comment]
Del commit anterior fueron 2hrs y monedas, redondeo a 3 hrs.
Total = 26 hs

**Comment by diejavrom** [comment]
Sumo 3hrs más del commit anterior.
Total = 29 hs

**Comment by nacho270** [comment]
Desarrollo comun ABM, carga datos teñido e impresion de lista de precios: 21 hs

Total acumulado= 50hs

**Comment by nacho270** [comment]
Sumo una hora mas.

Total acumulado = 51hs

**Comment by diejavrom** [comment]
Sumo 2 hrs más del commit anterior.
Total acumulado = 53hs

**Comment by diejavrom** [comment]
Sumo 1shr más del commit anterior.
Total acumulado = 54h

**Comment by diejavrom** [comment]
Sumo 2hs del commit anterior
Total acumulado = 56h

**Comment by nacho270** [comment]
Sumo 1 hora: Arreglo de datos, carga automatica de reproceso sin cargo, cambios en factura sin remito.

Total acumulado = 57hs

**Comment by diejavrom** [comment]
Sumo 3 hs: 2h mias y 1h de nacho
Total acumulado = 60hs

**Comment by diejavrom** [comment]
Sumo 3hs del commit anterior.
Total acumulado = 63hs

**Comment by diejavrom** [comment]
Sumo 2hs de testing/fix
Total acumulado = 65hs

**Comment by nacho270** [comment]
Sumo 1.5 hs.

Total acumulado: 66.5 hs.

**Comment by nacho270** [comment]
Sumo 1hs.

Total acumulad: 67.5hs

**Comment by diejavrom** [comment]
Sumo 2 hs del commit anterior.
Total acumulado: 69.5 hs

**Comment by nacho270** [comment]
Sumo 2 horas de reunion.

Total acumulado: 71,5 hs.

**Comment by diejavrom** [comment]
Sumo 1h lo que me llevó acomodar los métodos a raíz del agregado de Cotizacion + testing
Total acumulado: 72,5 hs

**Comment by nacho270** [comment]
Sumo 2.5 horas mas. Carga rapida de precios en teñido + columna resumen de definicion precio

Total acumulado: 75 hs

**Comment by diejavrom** [comment]
Sumo 2hs del commit anterior
Total acumulado: 77 hs

**Comment by nacho270** [comment]
Reunion: 1,5 x 2 = 3hs

Total acumulado = 80hs

**Comment by nacho270** [comment]
Puntos 1, 4, 6 y 14: 1 hora

Total acumulado = 81 hs.

**Comment by nacho270** [comment]
Envio de email: 30 minutos

Total acumulado: 81, 5 horas

**Comment by diejavrom** [comment]
commit anterior, puntos 5,8,9 y 11. Sumo 2.5 hs

Total acumulado: 84 hs

**Comment by nacho270** [comment]
Sumo 2 horas de: previsualizacion de lista de precios + envio de mail con adjunto + bug en jasper.

total acumulado: 86 hs

**Comment by diejavrom** [comment]
Sumo 1.5 hs del commit anterior.

Total acumulado: 87.5 hs

**Comment by diejavrom** [comment]
sumo 1h del commit anterior

Total acumulado: 88.5 hs

**Comment by nacho270** [comment]
Aumentador de precios: 4hs

Total acumulado: 92.5 hs

**Comment by diejavrom** [comment]
Agrego 2.5 hs del commit anterior.

Total acumulado: 95 hs

**Comment by diejavrom** [comment]
Sumo 2.5 hs de revisión/testing/ajustes entre ayer y hoy

Total acumulado: 97.5 hs

**Comment by nacho270** [comment]
Sumo 0.5 hs de fixes.

Total acumulado: 98 hs

**Comment by diejavrom** [comment]
Sumo 1h del commit anterior
Total acumulado: 99 hs

**Comment by diejavrom** [comment]
Sumo 6hs del sábado 19/09
Total acumulado: 105 hs

**Comment by nacho270** [comment]
Agrego 2 hs del commit anterior

Total acumulado: 107 hs.

**Comment by nacho270** [comment]
Agrego 0,5 hs al commit anterior.

Total acumulado = 107,5 hs

**Comment by diejavrom** [comment]
Commits anteriores (federación):   22/09 -> [4hs], 23/09 -> [3hs],  24/09 -> [3hs],  25/09 -> [2hs], 26/09 -> [3hs], 27/09 -> [2hs]
Total commit: 18 hs

Total acumulado = 125,5 hs

**Comment by diejavrom** [comment]
Sumo 2hs más del commit anterior 
Total acumulado: 127,5 hs

**Comment by nacho270** [comment]
Sumo 12 hs del deploy del martes.

Total acumulado: 139.5 hs
