### ISSUE TITLE
Mantenimiento

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTL#24]
Issue para ir cargando todas las tareas de soporte o mantenimiento.

**Comment by diejavrom** [comment]
El 08/10 se hizo:
- Se continuó con la migración de datos en la B se definió el proveedor y persona para CLAUDIA
- se resolvió un bug nuestro a nivel datos (cliente 165)
- Se investigó y corregió el bug del dialogo de factura al modificar los KG
- Se hizo un deploy
  Total: 2hs
  Total acumulado: 2hs

**Comment by nacho270** [comment]
El 10/10 se arreglaron bugs de materias primas hijas (1h)
- comentar todas las validaciones
- al agregar que no aparezcan los que ya están asignados a otro
- poder cambiar "tipo" de materia prima
- al asociar, que todos los hijos queden con el nombre del padre

Total acumulado: 3hs

**Comment by diejavrom** [comment]
Agrego 3hs del despliegue que hicimos el 03/11.

Total acumulado: 6hs

**Comment by nacho270** [comment]
-------------------------------- NUEVO INICIO -------------------------------

Reunion 13/2: 6hs

Total acumulado: 6hs

**Comment by nacho270** [comment]
Reunion 26/2: 8hs

Total acumulado: 14hs

**Comment by nacho270** [comment]
Deploy federacion ODT: 4hs.

Total acumulado: 18hs

**Comment by nacho270** [comment]
Fixes impresion ODT: 2hs.

Total acumulado: 20hs.

**Comment by diejavrom** [comment]
Fuimos a la fábrica el 19/02.
Hicimos versión con los commits
https://github.com/nacho270/GTL/commit/6fa4106b6995031016a1ef811e9d85bfd9c45512
https://github.com/nacho270/GTL/commit/96c5247e34019b70280d76f19e1c021ff64a6780
Total: 7hs

Total acumulado: 27hs

**Comment by diejavrom** [comment]
Fuimos a la fábrica el 30/04
Hicimos versión con el commit
ef6c03fc84e0328e3f2781df5d3a7739abdc7442
Total: 8hs
Total acumulado: 35hs

**Comment by diejavrom** [comment]
Call para el análisis de Ingreso de Remito Unificado.
Total: 2hs
Total acumulado: 37hs

**Comment by diejavrom** [comment]
Sumo 8hs de la reunión en la fábrica el día 31/05/2016.
Total acumulado: 45hs

**Comment by diejavrom** [comment]
-------------------------------- NUEVO INICIO -------------------------------

**Comment by diejavrom** [comment]
Sumo 7hs de la reunión en la fábrica el día 20/08.
Total acumulado: 7hs

**Comment by diejavrom** [comment]
Sumo 7hs de la reunión del 13/09 en la casa de Diego.
Total acumulado: 14hs

**Comment by diejavrom** [comment]
Sumo 5hs de la reunión del 22/10 en la fábrica.
Total acumulado: 19hs

===============================NUEVO INICIO ============

**Comment by diejavrom** [comment]
Sumo 4hs del deploy del 19/01
Total acumulado: 4hs

**Comment by diejavrom** [comment]
Sumo 3hs de configuración del server nuevo de Test.
Total acumulado: 7hs

**Comment by diejavrom** [comment]
Sumo 8hs de reunión el día 27/01, configuramos el viejo server de test,  relevamos próximos pasos  y revisamos aplicación gtl client.
Total acumulado:15hs

**Comment by diejavrom** [comment]
Sumo 10 hrs de la reunión del 11/02. Probamos la impresión, hicimos nuevas versiones, relevamos los siguientes issues
https://github.com/nacho270/GTLLiteClient/issues/11
https://github.com/nacho270/GTL/issues/95
https://github.com/nacho270/GTL/issues/96
y tratamos de dejar operativa la rasperry.
Total acumulado: 25hrs

**Comment by diejavrom** [comment]
Sumo 10hrs de la reunión del 16/02.
Se hicieron varios cambios, ver commits:
https://github.com/nacho270/GTL/commit/0bfac1a5fc35824fdbf6299b98f7bed8579d3065
https://github.com/nacho270/GTLLiteClient/commit/c6a0958c7b165023fe46f42decb9d71f2a0eb6e8
y también nos llevamos los siguientes issues para hacer:
https://github.com/nacho270/GTL/issues/97 		
https://github.com/nacho270/GTL/issues/98
https://github.com/nacho270/GTLLiteClient/issues/12	
https://github.com/nacho270/GTLLiteClient/issues/13	
https://github.com/nacho270/GTLLiteClient/issues/14

Total acumulado: 35hrs

**Comment by diejavrom** [comment]
Sumo 8hs de la reunión del 21/02.
Actualizamos certificados de AFIP, dejamos disponible el Backup de DB e hicimos un fix en GTLLite. Ver commits:
https://github.com/nacho270/GTL/commit/edbb4d3099a7ee51ddf328e14b06380eeaffa741
https://github.com/nacho270/GTL/commits
y también nos llevamos los siguientes issues para hacer
https://github.com/nacho270/GTL/issues/99
https://github.com/nacho270/GTL/issues/100
https://github.com/nacho270/GTL/issues/101
https://github.com/nacho270/GTL/issues/102
https://github.com/nacho270/GTLLiteClient/issues/15
https://github.com/nacho270/GTLLiteClient/issues/16

Total acumulado: 43hrs

**Comment by diejavrom** [comment]
Sumo 1.5 hs de puesta a punto del nuevo server de test el 01/03
Total acumulado: 44.5hrs

**Comment by diejavrom** [comment]
Sumo 7hrs. de la reunión del 14/03.
Hicimos versión nueva con todo esto

En GTL:
- Seteo de metros en el doble faz de la impresión de la ficha de remito
- Bug Fix al mostrar los metros de entrada de la ODT
- Bug Fix en el módulo "Estado de Producción" con el tema de las fechas y estados
- Bug Fix con el seteo de la fecha de la ODT (se estaba grabando la fecha del RE)
(ver commit fa37f9fe5d4025099a18e9e171aebfe94445bf4c)

En GTL Lite:
- Bug Fix en el módulo de asignación de metros al sincronizar objetos
- Botón salir del input del lector de CB ahora sale del sistema
(ver commit https://github.com/nacho270/GTLLiteClient/commit/d6ae45581131e442465f6abc541474529f59836f)

Además, nos llevamos los siguientes issues para hacer

https://github.com/nacho270/GTLLiteClient/issues/17
https://github.com/nacho270/GTLLiteClient/issues/18
https://github.com/nacho270/GTL/issues/103
https://github.com/nacho270/GTL/issues/104
https://github.com/nacho270/GTL/issues/105


Total acumulado: 51.5 hrs

**Comment by diejavrom** [comment]
Sumo 7hrs de la reunión del 21/03.
Hicimos versión nueva con todo esto:
En GTL:

- Bug Fix en el módulo de lista de precios al setear los anchos
- Bug Fix en el cálculo de seguro en la carga de factura
- Bug Fix en el dato de gramaje y metros de la impresión de solo encabezado de ODT
(ver commmit https://github.com/nacho270/GTL/commit/d75243f7feb8184b3760bdadea6e00be31929435)

En GTL Lite:
- Bug Fix en los botones subir/bajar + seteo de modo de selección simple en la tabla del módulo de cosido
- Seteo correcto de piezas y metros en el módulo de cosido.

(ver commit https://github.com/nacho270/GTLLiteClient/commit/ed7c1335b99b3f04de1f866e782446159630b358 )

Además nos llevamos los siguientes issues para hacer:

https://github.com/nacho270/GTL/issues/103 (ya existía, hubo cambio de alcance)
https://github.com/nacho270/GTL/issues/107
https://github.com/nacho270/GTL/issues/108
https://github.com/nacho270/GTL/issues/109
https://github.com/nacho270/GTL/issues/110
https://github.com/nacho270/GTL/issues/111
https://github.com/nacho270/GTL/issues/112
https://github.com/nacho270/GTLLiteClient/issues/19

Total acumulado: 58.5 hrs

**Comment by diejavrom** [comment]
Sumo 7hrs de la reunión del 18/04.
Hicimos versión nueva con todo esto:
En GTL:

Bug Fix en el seteo del ancho del módulo de remitos de entrada y también en el modo edición de lista de precios.
(ver commmit https://github.com/nacho270/GTL/commit/05579573078066e1f120fe6d8c3b8e644b4e2829)
En GTL Lite:

quitamos validación de máquina al pasar por sector 
(ver commit https://github.com/nacho270/GTLLiteClient/commit/b60750f02a5a0aa2409684077761d5028486242f )

Además nos llevamos los siguientes issues para hacer:
#116 
nacho270/GTLLiteClient#20

Total acumulado: 65.5 hrs

**Comment by diejavrom** [comment]
==============NUEVO INICIO====================
Sumo 7hs de la reunión del 02/05
Hicimos versión con todo esto:
En GTL:
Bug fix para que se dispare la notificación al pasar a estado EN_OFICINA
(ver commit https://github.com/nacho270/GTL/commit/b145f2bdd50088befe54d32cfe26ca9e6e51e83c)

En GTLLite:
ajustes sobre el nuevo módulo de sector seco
(ver commit https://github.com/nacho270/GTLLiteClient/commit/07845a962af7be4b1bcfbced7f9518186795e2e5)

Además nos llevamos algunos cambios sobre el issue :
https://github.com/nacho270/GTLLiteClient/issues/20
y terminar el siguiente:
https://github.com/nacho270/GTL/issues/111

Total acumulado: 7hs

**Comment by diejavrom** [comment]
Sumo 9hs de la reunión del 16/05
Hicimos versión con todo esto:

+ se cambiaron cosas de la impresión de la ODT (falta completar)
+ se ejecutaron scripts
+ se agregó el producto Fraccionado

Además nos llevamos los siguientes issues para hacer:

#120 ODT - Impresión de Secuencia de Trabajo
#121 Remito de Entrada - Cambios en el dialogo de alta/consulta/edición
#122 Agregado de logo en informe
#123 ODT - Refactor en la obtención de códigos
#124 Posibilidad de cargar un RE con una ODT sin producto 
https://github.com/nacho270/GTLLiteClient/issues/21 Impresión de etiquetas de piezas - Agregar texto

Total acumulado: 16hs

**Comment by diejavrom** [comment]
Sumo 7hs de la reunión del 13/06.
Hicimos versión, con arreglos menores, ver commit 24cb3027b8e75c00a04b3fb02be97fdc86c64b81
y nos llevamos los siguientes issues para hacer:

#126 Crear movimiento al ingresar un RS de tipo DEVOLUCION/REPROCESO S/CARGO
#127 Quitar campos en el dialogo de alta/consulta de RS
#128 Agregar ODT en el módulo de cuentas de clientes
#129 Corregir nros de ordenes repetidos para Orden de Pago de Personas
#130 Quitar gramaje de Artículo
#131 ODTs revisión de aquellas que tuvieron salida parcialmente

Total acumulado: 23hs

**Comment by diejavrom** [comment]
==============NUEVO INICIO====================

**Comment by diejavrom** [comment]
Sumo 7hs de la reunión del 01/08, hicimos versión nueva y los siguientes cambios:

https://github.com/nacho270/GTL/commit/61b4f1b35129d8790df3e01d7e8c1d19f24c7ff2

y nos llevamos los siguientes issues para hacer:

https://github.com/nacho270/GTL/issues/136
https://github.com/nacho270/GTL/issues/137
https://github.com/nacho270/GTL/issues/138
https://github.com/nacho270/GTL/issues/140
https://github.com/nacho270/GTLLiteClient/issues/22
https://github.com/nacho270/GTL/issues/139
https://github.com/nacho270/GTLLiteClient/issues/23

Total acumulado: 7hs

**Comment by diejavrom** [comment]
Sumo 7hs de la reunión 17/08. Nos llevamos los siguientes issues para hacer 
#143 
#144 
#145 
#146 
Total acumulado: 14 hs

**Comment by diejavrom** [comment]
Sumo 5hs de la reunión del 05/09. Nos llevamos los siguientes issues para hacer:

https://github.com/nacho270/GTL/issues/148
https://github.com/nacho270/GTL/issues/149
https://github.com/nacho270/GTL/issues/150
https://github.com/nacho270/GTL/issues/151
https://github.com/nacho270/GTL/issues/152
https://github.com/nacho270/GTL/issues/153

total acumulado: 19 hs.

**Comment by diejavrom** [comment]
Sumo 6hs de la reunión del 10/10. Nos llevamos los siguientes issues para hacer:

https://github.com/nacho270/GTL/issues/154
https://github.com/nacho270/GTL/issues/155
https://github.com/nacho270/GTL/issues/156
https://github.com/nacho270/GTL/issues/157
https://github.com/nacho270/GTL/issues/158
https://github.com/nacho270/GTL/issues/159
https://github.com/nacho270/GTL/issues/160
https://github.com/nacho270/GTL/issues/161

Total acumulado: 25 hs.

**Comment by diejavrom** [comment]
==============NUEVO INICIO====================
Sumo 5hs de la reunión del 06/11. Nos llevamos los siguientes issues para hacer:

https://github.com/nacho270/GTL/issues/162
https://github.com/nacho270/GTL/issues/163
https://github.com/nacho270/GTL/issues/164
https://github.com/nacho270/GTL/issues/165
https://github.com/nacho270/GTL/issues/166

Total acumulado: 5 hs.

**Comment by diejavrom** [comment]
sumo 0.5 hs del despliegue (remoto) de la versión con los issues:
#162
#163
#164
#165
#166
#167 
Además hice un fix sobre lo que devuelve el lector y mandé el mail con las cosas nuevas.

Total acumulado: 5.5 hs

**Comment by diejavrom** [comment]
sumo 9 hrs de reunión del 01/12/2018 en la fábrica. Nos llevamos los siguientes issues:
#170 
#171  
#172 
#173 
además hicimos un fix en la impresión de remito B y también revisamos un caso de "salteo" de numeración de FC que no pudimos reproducir entre otras cosas (Ver commit 3823ef2f1abb3cd30c9d2047467eefd496a9d64d)

Total acumulado: 14.5 hs

**Comment by diejavrom** [comment]
Sumo 2hs de soporte por el cambio de router que nos obligó a levantar el jboss de la B en el port 8180.

Total acumulado: 16.5 hs

**Comment by diejavrom** [comment]
Cierro este ticket, todo lo pendiente queda en el #178
