### ISSUE TITLE
Ajuste en Mail de Envio de Factura en Sistema B [1h]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTL#50]
Se pide hacer los siguientes ajustes en el mail de envío de FC en el sistema B:
- Asunto: actualmente dice "Factura N° [NRO_FACTURA]" se debe cambiar por "Importe Rto N° [NRO_REMITO]"
- Cuerpo del mail: cambiar la frase que dice "..adjuntamos la Factura N° [NRO_FACTURA]". por "adjuntamos importe correspondiente al remito N° [NRO_REMITO]."
- Nombre del adjunto: actualmente el nombre del archivo es "factura_[NRO_FACTURA].pdf" cambiar por "importe_[NRO_FACTURA].pdf"

**Comment by nacho270** [comment]
1 hora
