### ISSUE TITLE
Ajuste de Texto en la Tabla de Movimientos de la Impresión del Resumen de Cuenta en el Sistema B [30m]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTL#55]
En la impresión del resumen de cuenta del sistema B se pide no mostrar los datos de Factura, ejemplo, actualmente se muestra:
"12/01/2016 - RTO 1234 - FC 156823"
debería quedar como
"12/01/2016 - RTO 1234"

**Comment by nacho270** [comment]
30  minutos
