### ISSUE TITLE
Ajustes en el módulo de Estado de Producción [1h]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTL#63]
En el módulo "Estado de Producción" se piden los siguientes ajustes:
- Achicar el título rojo "Estado de Producción"
- Modificar el toString de la ODT, debería quedar con los siguientes datos:
  - código ODT
  - número de cliente, ejemplo "CL:6"
  - Artículo, ejemplo, "ART: AP 2.50"
  - Proceso, ejemplo "P: Estampado -1999-."
  - Total KG, ejemplo "302 KG" 
  - Total Metros, ejemplo "1629 MTS" 
- Hacer más ancho "ODTs Disponibles", la idea es que el toString de la ODT entre sólo en 2 líneas.

**Comment by nacho270** [comment]
Total: 1h
