### ISSUE TITLE
Remito unificado [39h]

### ISSUE THREAD

**Issue by nacho270** [nacho270/GTL#66]
- Requerimientos:
- Carga de Remito de Entrada sólo de la A pero para usar en la B:
- La carga debe hacerse únicamente desde la A, también se hace en la A la parte de las transiciones de máquina.
- La asignación del mismo debe hacerse de cualquier sistema.
- Se debe proveer una operación desde la B para "desasignarlo" y que quede disponible nuevamente en caso de error.
  Se debe poder hacer con las mismas reglas que tenemos hoy en día al eliminar una factura.
  Idem anterior pero desde la A. En este caso si el REM tiene asociada una FC ya no se podría.
- Detalles de Implementación:
  - Si el REM tiene RS, FC o Secuencia ODT => no se puede tomar desde la B.
  - No vamos a permitir tomar remitos parciales.
  - Quitar módulo del remito de entrada en la B.
  - La Tabla T_REMITO no se federa y nos manejamos copiando y borrando datos.
  - La B consulta los remitos lo hace a través de un web service expuesto en la A
    Los objetos deben ser transient lo que no esté federado. Devolverá el listado de DetallePiezaRemitoEntradaSinSalida
  - Otro servicio que reemplaza la llamada de la JDialogSeleccionarRemitoEntrada línea 187, además hacemos un refactor en la A para
    que se devuelva una lista de ids.
  - Otro servicio que permita borrar un RE (en cascada) desde la B, indicando que ya se procesó en la B.
    => Validar que en la B sólo se pueda dar salida a un remito completo
  - Otro Servicio para insertar un Remito de entrada en la A desde la B, esto se usará cuando se quiera
    desasociar un remito desde la B. 
    - A nivel Refactor, utilizararemos Bussiness Delegate.
  - Federar Tarima
  - Al momento de desasignar un remito desde la B, se inserta el registro nuevamente en la A y ahí puede
    pasar que las ODTs no sean las mismas.
      => Recordar borrar el Remito de Entrada en la B después de pasarlo a la A y también el Remito de Salida
- Consultas:
  - Vamos a permitir tomar remitos parciales desde la B? NO, es remito completo.
  - Desde qué módulo se volverá a pasar el RE a la A? hacer un módulo especial para esta devolución, incluso puede volver a la A teniendo FC en la B, en ese caso, hay que borrar la FC.
  - Los nros de ODT se regeneran o se intentan copiar y cuando no se pueda se regeneran? 
    - Nunca se regeneran, en la B se copia el nro de ODT y la A guarda la última ODT guardada y calcula el próximo a partir de ahí.
  # nuevas preguntas
  - (En la B) Ver si se pueden eliminar los remitos viejos y al poner esta funcionalidad en PROD esperamos que no haya remitos de salida sin facturar.
    Porque los Remitos de salida sin FC son los candidatos a ser devueltos a la A.

**Comment by nacho270** [comment]
Tiempo total: 1h

**Comment by nacho270** [comment]
Tiempo total: 2hs

**Comment by nacho270** [comment]
Agrego 2,5 hs

Tiempo total: 4,5hs

**Comment by diejavrom** [comment]
sumo 3hs: seteo de workspace en la maq virtual + configuración de branch en mi notebook (no podía hacer push) + revisión e implementación del query.

Tiempo total: 7,5hs

**Comment by nacho270** [comment]
Sumo 1h: Desarrollo inicial de modulo de retorno de RE.

Total: 8,5 hs

**Comment by nacho270** [comment]
Sumo 4hs: Retorno de remito entrada (falta)

Total: 12,5 hs

**Comment by nacho270** [comment]
Sumo: 0.5 h.

Total: 13 hs

**Comment by diejavrom** [comment]
Sumo 2.5 hs del commit
d1b91cd20ffd49caff2be38571f9d0effb707f4c
Total: 15.5 hs

**Comment by diejavrom** [comment]
Sumo 2 hs del commit
ec36dda890d0f830adbbeb748ad86e6e42da06cf
Total: 17.5 hs

**Comment by nacho270** [comment]
Sumo 2hs.

Total: 19,5hs

**Comment by diejavrom** [comment]
Sumo 2.5 hs del commit
5b7680274fa5e98ca517ad2663a25cdc51d8b1e9
Total: 22 hs

**Comment by diejavrom** [comment]
Sumo 1.5 del commit
440fad1d0e53dbac2632cd414f643ba73873e8ae
Total: 23.5

**Comment by nacho270** [comment]
Sumo 1h: Eliminacion de remito forzada y validacion de seleccionar remito completo para dar salida en la B.

Total: 24,5 hs

**Comment by nacho270** [comment]
Sumo 2hs de reunion + 0,5 h de arreglos de ayer y hoy,

Total: 27 hs

**Comment by nacho270** [comment]
Sumo 2hs.

Total: 29hs

**Comment by diejavrom** [comment]
Sumo 3.5 hs del commit
f378b8eb78a8660d2bd5bab8ad98ae76301d1905
Total: 32.5hs

**Comment by diejavrom** [comment]
Sumo 2 hs de las pruebas y ajustes de RE sin Secuencia ODT, commit
480f6151d0d0a90ca4fe97304eb75b37fc44238b
Total: 34.5hs

**Comment by diejavrom** [comment]
Sumo 2hs de las pruebas y ajustes del RE con Secuencia ODT, commit
b4005977de1539eb62fc772431bcafad60cf7251
Total: 36.5

**Comment by diejavrom** [comment]
Sumo 2.5hs de preparación de script para borrar RE (viejos) en A/B y tmb borrar RS sin FC en B, ver commit 
3946a7c3ee97e7f9519a266e5398c98c1003d573

Total: 39hs

**Comment by diejavrom** [comment]
hicimos deploy de esto el 20/08. Cierro el issue
