### ISSUE TITLE
ABM de Fórmulas - Impresión - Incorporar químicos de Descrude [2h]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTL#76]
Incorporar los químicos del Descrude en la impresión resumen del ABM de Fórmulas. El cálculo de las cantidades debe hacerse en base a la cantidad de KG ingresadas manualmente y tomando el Tipo de Artículo de la fórmula (de Teñido) seleccionada.

**Comment by nacho270** [comment]
Total 2h
