### ISSUE TITLE
Remito de Salida/Orden de Pago - Agregar flag/estado "Entregado" + Cód de Barras [19h]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTL#78]
Se pide agregar un flag/estado de "Entregado" en Remito de Salida y Orden de Pago de Proveedor.
También se pide imprimir un código de barras con el siguiente formato:
[PREFIJO][NRO_DOCUMENTO][IDENTIFICADOR_SISTEMA]

**Comment by nacho270** [comment]
10 hs: Investigacion + puesta en funcionamiento raspberry

Total: 10 hs

**Comment by nacho270** [comment]
Agrego 1 hora de desarrollo primitivo de UI.

Total: 11 hs

**Comment by nacho270** [comment]
1hs: Toques de UI

Total: 12 hs

**Comment by nacho270** [comment]
30m: Impresion codigos de barra (El de RS hay que medirlo en la fabrica con la plantilla)

Total: 12, 5 hs

**Comment by nacho270** [comment]
1,5h: Cliente web service + Flag entregado en ODP y RS

Total: 14 hs

**Comment by nacho270** [comment]
1h: Agregado logica de flag "entregado" + retoques UI

Total: 15hs

**Comment by nacho270** [comment]
2h. Codigos de respuesta  + logger + deploy en raspberry para que arranque solo.

Total: 17hs

**Comment by nacho270** [comment]
1h. Nombre terminal + columna back.

Total: 18 hs

**Comment by nacho270** [comment]
1h: Columna "entregado" en cuenta cliente + sufijo tipo sistema en codigo de barras.

Total: 19 hs
