### ISSUE TITLE
Código de barras en órdenes de pago a personas en TEST [1h]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTL#88]
Las órdenes de pago a personas (sucede en TEST, chequear también en la A) salen sin código de barras.

**Comment by nacho270** [comment]
Se hizo para la A y la B.
Total: 30m

**Comment by nacho270** [comment]
Se agrego salida y reingreso por terminal + columna en modulo de cuentas persona.

Total acumulado: 1h.
