### ISSUE TITLE
Desarrollo conexion con afip

### ISSUE THREAD

**Issue by nacho270** [nacho270/GTL#9]

**Comment by nacho270** [comment]
Por ahora 3hs

**Comment by nacho270** [comment]
Por ahora 6hs en total

**Comment by diejavrom** [comment]
fueron 6 hrs aprox

**Comment by nacho270** [comment]
3hs
Pantallas de:
- autorizacion para facturas pendientes
- visualizacion de estado de servicios

Total acumulado: 6 + 6 + 3= 15 hs

**Comment by nacho270** [comment]
Migracion de impresion de factura: 4hs

Total acumulado: 19hs

**Comment by diejavrom** [comment]
Me olvidé de loguear las horas de esto (2 hrs) 
- Mejora en el manejo de exepciones de AFIP
- Agrego validación al anular una Corrección Factura
- Envío de comprobantes relacionados al autorizar un documento.

Total: 8 hrs

**Comment by nacho270** [comment]
O sea que el total es 27 hs

**Comment by diejavrom** [comment]
Logueo 3 hrs correspondientes al commit de arriba (ya logré autorizar 3 facturas en test!)

Van 30 hs en total.

**Comment by diejavrom** [comment]
Agrego 8 hrs (4 hrs c/u) correspondientes al setup en la fábrica y los cambios que hicimos ahí.

Van 38 hs en total.

**Comment by nacho270** [comment]
Sumo 4 hs de correcciones.

Total: 42 hs

**Comment by nacho270** [comment]
Sumo 4 hs de agregado de numero de sucursal, correcciones de impresion y correcciones varias.

Total: 46hs

**Comment by diejavrom** [comment]
sumo 2hs del commit anterior.
Total: 48 hs.

**Comment by diejavrom** [comment]
sumo 2hs del commit anterior.
Total: 50 hs

**Comment by nacho270** [comment]
Sumo horas:
2 hs desarrollo codigo de barras
4 hs (2 javi, 2 nacho) de investigacion de porque no funciono
6 hs (3 javi, 3 nacho) del sabado

Total: 12 hs

Total general: 62 hs

**Comment by nacho270** [comment]
Cerrado y cobrado
