### ISSUE TITLE
Implementar módulo de asignación de terminal/módulo de GTLLiteClient [3h]

### ISSUE THREAD

**Issue by diejavrom** [nacho270/GTL#94]
Ver de hacer sólo un módulo que maneja la asociación entre rasperry/pc y módulo para que después cuando se inicie GTLLiteClient se haga con el módulo configurado. Preparar GTLLiteCliente para que sea compatible con ese mecanismo.

**Comment by nacho270** [comment]
Tiempo total: 3h
